module.exports = function(grunt){
  grunt.initConfig({
    uglify:{
      my_target:{
        files:{
          "assets/js/script.min.js":"assets/js/script.js"
        }
      }
    },
    sass:{
      options:{
        style:"compressed"
      },
      dist:{
        files:{
          "assets/css/style.css":"assets/sass/style.scss"
        }
      }
    },
    watch:{
      options:{
        livereload:460
      },
      sass:{
        files:"assets/sass/style.scss",
        tasks:"sass",
        reload:false
      },
      uglify:{
        files:"assets/js/script.js",
        tasks:"uglify",
        reload:false
      },
      js:{
        files:"assets/js/script.min.js",
        reload:true
      },
      css:{
        files:"assets/css/style.css",
        reload:true
      },
      php:{
        files:"**/*.php",
        reload:true
      }
    }
  });
  grunt.loadNpmTasks("grunt-contrib-uglify");
  grunt.loadNpmTasks("grunt-contrib-sass");
  grunt.loadNpmTasks("grunt-contrib-watch");

  grunt.registerTask("default",["watch"]);
}
